name: ci-workflow

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      app:
        type: string
        required: true
      stack:
        type: string
        required: true
      ecr_region:
        type: string
        required: true
    secrets:
      aws_actions_role:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # this makes the babel-jest-react magic happen and means all tests pass. If this is set to 
      # development then some tests will fail.
      NODE_ENV: "test"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.ecr_region }}
          role-to-assume: ${{ secrets.aws_actions_role }}
      - uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          architecture: 'x64'
      - run: |
          source ./setup.sh ${{ inputs.env }} ${{ inputs.stack }} ${{ inputs.app }} ${{ inputs.ecr_region }}
          yarn install
          yarn lint
          yarn test
