name: ci-ror-workflow

on:
  workflow_call:
    inputs:
      env:
        description: 'the environment'     
        type: string
        default: 'dev'
        required: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Test
        run: |
          docker-compose -f docker-compose.ci.yml -p 123 build web
          docker-compose -f docker-compose.ci.yml -p 123 run -u $(id -u) \
            -e HOME=/tmp -e RAILS_ENV=test web \
            bundle exec rspec --format RspecJunitFormatter --out results.xml \
            --format progress --format documentation
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/results.xml'
      - name: collect unit-test artefacts
        run: |
          mkdir unit-test-artefacts
          cp coverage/.resultset.json unit-test-artefacts/.resultset.json
          cp coverage/coverage.json unit-test-artefacts/coverage.json
          cp results.xml unit-test-artefacts/results.xml

          ls -lah unit-test-artefacts
      - name: Cache unit-test artefacts
        uses: actions/cache@v2
        with:
          path: unit-test-artefacts
          key: unit-test-artefacts-${{ github.run_number }}
