name: feature-test-pack-workflow

on:
  workflow_call:
    inputs:
      watchman_repo:
        type: string
        required: true
        description: watchman repository follwing the format - {org}/{repo}
      env:
        type: string
        required: true
        description: environment. eg. dev|uat|pre-prod|prod
      test_packs:
        type: string
        required: true
        description: test packs json. eg. [{\"test_pack\":\"olaf_features\"},{\"test_pack\":\"wishlist_features\"}]
      browser:
        type: string
        required: false
        default: headless
    secrets:
      grid_git_grid_token:
        required: true

jobs:
  run-test-pack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value:
          - ${{ fromJson(inputs.test_packs) }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - run: |
          # checkout watchman repo using git
          git clone https://${{ secrets.grid_git_grid_token }}@github.com/${{ inputs.watchman_repo }}.git 
          cd watchman/features
          BUNDLE_GEMFILE="${{ github.workspace }}/watchman/Gemfile"
          bundle install
          echo "here's the matrix value"
          echo ${{ matrix.value.test_pack }}
          bundle exec cucumber ./${{ matrix.value.test_pack }} ENVIRONMENT=${{ inputs.env }} BROWSER=${{ inputs.browser }} --format json --out=cucumber-report.json -q -f pretty
